"""Cookie 辅助模块 - 自动获取网站 Cookie

Netscape Cookie 文件格式（每行）：
    domain  domain_specified  path  secure  expires  name  value
    - domain_specified: TRUE 如果 domain 以 . 开头
    - secure: TRUE/FALSE
    - expires: Unix 时间戳，0 表示会话 Cookie
"""

import os
import tempfile
from pathlib import Path
from typing import Optional


def save_cookies_netscape(cookies: list, domain_filter: str, filepath: str) -> bool:
    """将 Playwright Cookie 列表保存为 yt-dlp 兼容的 Netscape 格式

    Args:
        cookies: Playwright cookies list
        domain_filter: 只保存包含此域名的 cookie
        filepath: 输出文件路径

    Returns:
        是否成功
    """
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write(f"# Generated by VideoCrawler for {domain_filter}\n\n")

            for c in cookies:
                cookie_domain = c.get("domain", "")
                if domain_filter not in cookie_domain:
                    continue

                name = c.get("name", "")
                # 跳过空 name 的 cookie
                if not name:
                    continue

                value = c.get("value", "")
                path = c.get("path", "/")

                # domain_specified: TRUE 当 domain 以 . 开头
                has_dot = cookie_domain.startswith(".")
                domain_specified = "TRUE" if has_dot else "FALSE"

                # secure
                secure = "TRUE" if c.get("secure") else "FALSE"

                # expires: 0 表示会话 Cookie
                expires = c.get("expires", 0)
                if expires is None or expires < 0:
                    expires = 0
                expires = str(int(expires))

                # Netscape 格式: domain domain_specified path secure expires name value
                f.write(
                    f"{cookie_domain}\t{domain_specified}\t{path}\t"
                    f"{secure}\t{expires}\t{name}\t{value}\n"
                )

        return os.path.getsize(filepath) > 100
    except Exception as e:
        print(f"[cookie] Save error: {e}")
        return False


def fetch_cookies_with_playwright(
    url: str,
    domain: str,
    output_file: Optional[str] = None,
) -> Optional[str]:
    """用 Playwright 启动隐身浏览器访问网站，获取 Cookie

    Args:
        url: 要访问的页面 URL
        domain: 要保存的 Cookie 域名过滤
        output_file: 输出文件路径，None 则自动生成临时文件

    Returns:
        Cookie 文件路径，失败则返回 None
    """
    if output_file is None:
        output_file = os.path.join(tempfile.gettempdir(), "vc_cookies_playwright.txt")

    try:
        from playwright.sync_api import sync_playwright

        with sync_playwright() as p:
            browser = p.chromium.launch(
                headless=True,
                args=[
                    "--no-sandbox",
                    "--disable-blink-features=AutomationControlled",
                ],
            )
            context = browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/120.0.0.0 Safari/537.36"
                ),
                viewport={"width": 1920, "height": 1080},
            )
            page = context.new_page()

            # 使用 'load' 事件（比 networkidle 快很多）
            page.goto(url, wait_until="load", timeout=20000)
            # 额外等待 JS 设置 cookie
            page.wait_for_timeout(3000)

            cookies = context.cookies()
            browser.close()

        if not cookies:
            return None

        if save_cookies_netscape(cookies, domain, output_file):
            return output_file

    except Exception as e:
        print(f"[cookie] Playwright error: {e}")

    return None


def fetch_douyin_cookies(output_file: Optional[str] = None) -> Optional[str]:
    """获取抖音 Cookie（用于视频提取和下载）"""
    return fetch_cookies_with_playwright(
        url="https://www.douyin.com/",
        domain="douyin.com",
        output_file=output_file,
    )


# 登录态 Cookie 名（任一存在即认为已登录）
LOGIN_COOKIE_NAMES = ("sessionid_ss", "sessionid", "sid_tt", "sid_guard",
                      "passport_auth_token")


def has_login_cookie(cookies: list) -> bool:
    """判断 cookie 列表中是否包含抖音登录态"""
    names = {c.get("name") for c in cookies or []}
    return bool(names & set(LOGIN_COOKIE_NAMES))


def fetch_douyin_cookies_interactive(
    output_file: Optional[str] = None,
    wait_seconds: int = 90,
    channel: Optional[str] = "chromium",
    progress_cb=None,
) -> dict:
    """交互式获取抖音登录 Cookie：

    弹出真浏览器窗口打开抖音首页，用户扫码/登录。每 1.5 秒检测登录态
    （sessionid_ss / sessionid / sid_tt / sid_guard），检测到即收集 Cookie
    结束；等待 wait_seconds 秒超时则收集基础 Cookie（继续可用，但私密
    视频可能仍受限）。

    Args:
        output_file: Netscape 保存路径
        wait_seconds: 最长等待登录秒数
        channel: 浏览器通道 chromium/msedge
        progress_cb: 回调 (msg: str)

    Returns:
        {"success": bool, "logged_in": bool, "file": str, "message": str}
    """
    import time as _time
    from core.douyin_extractor import (
        DOUYIN_UA, _STEALTH_JS, find_chromium_executable)

    if output_file is None:
        output_file = os.path.join(
            os.path.expanduser("~"), ".video_crawler",
            "douyin_cookies.txt")
    os.makedirs(os.path.dirname(output_file), exist_ok=True)

    if progress_cb:
        progress_cb("启动浏览器窗口（请扫码登录抖音）...")

    try:
        from playwright.sync_api import sync_playwright

        with sync_playwright() as p:
            args = [
                "--disable-blink-features=AutomationControlled",
                "--no-first-run", "--no-sandbox", "--lang=zh-CN",
            ]
            launch_kwargs = {"headless": False, "args": args}
            exe = find_chromium_executable()
            if exe:
                # 打包环境修复：显式指向本机 Chromium
                launch_kwargs["executable_path"] = exe
            elif channel:
                launch_kwargs["channel"] = channel
            browser = p.chromium.launch(**launch_kwargs)
            context = browser.new_context(
                user_agent=DOUYIN_UA,
                viewport={"width": 1280, "height": 900},
                locale="zh-CN", timezone_id="Asia/Shanghai",
            )
            context.add_init_script(_STEALTH_JS)
            page = context.new_page()
            page.goto("https://www.douyin.com/", wait_until="domcontentloaded",
                      timeout=40000)
            page.wait_for_timeout(3000)

            logged_in = False
            deadline = _time.time() + wait_seconds
            while _time.time() < deadline:
                # 每 1.5s 检测登录态
                try:
                    cookies = [dict(c) for c in context.cookies()
                               if "douyin" in c.get("domain", "")]
                    if has_login_cookie(cookies):
                        logged_in = True
                        break
                    page.wait_for_timeout(1500)
                except Exception:
                    # 页面意外关闭（用户手动关窗/竞态）则停止等待
                    break

            cookies = [dict(c) for c in context.cookies()
                       if "douyin" in c.get("domain", "")]
            browser.close()

        if not cookies:
            if progress_cb:
                progress_cb("未获取到任何 Cookie")
            return {"success": False, "logged_in": False,
                    "file": "", "message": "未获取到 Cookie"}

        ok = save_cookies_netscape(cookies, "douyin", output_file)
        if not ok:
            ok = save_cookies_netscape(cookies, "", output_file)
        if not ok:
            return {"success": False, "logged_in": logged_in,
                    "file": "", "message": "Cookie 保存失败"}
        if logged_in:
            msg = "登录态获取成功，已保存登录 Cookie"
        else:
            msg = (f"未检测到登录（{wait_seconds}s 超时），"
                   "已保存基础 Cookie（私密视频可能仍需要登录）")
        if progress_cb:
            progress_cb(msg)
        return {"success": True, "logged_in": logged_in,
                "file": output_file, "message": msg}

    except Exception as e:
        if progress_cb:
            progress_cb(f"失败: {e}")
        return {"success": False, "logged_in": False,
                "file": "", "message": f"浏览器失败: {e}"}


def fetch_tiktok_cookies(output_file: Optional[str] = None) -> Optional[str]:
    """获取 TikTok Cookie"""
    return fetch_cookies_with_playwright(
        url="https://www.tiktok.com/",
        domain="tiktok.com",
        output_file=output_file,
    )
