"""Cookie 辅助模块 - 自动获取网站 Cookie

Netscape Cookie 文件格式（每行）：
    domain  domain_specified  path  secure  expires  name  value
    - domain_specified: TRUE 如果 domain 以 . 开头
    - secure: TRUE/FALSE
    - expires: Unix 时间戳，0 表示会话 Cookie
"""

import os
import tempfile
from pathlib import Path
from typing import Optional


def save_cookies_netscape(cookies: list, domain_filter: str, filepath: str) -> bool:
    """将 Playwright Cookie 列表保存为 yt-dlp 兼容的 Netscape 格式

    Args:
        cookies: Playwright cookies list
        domain_filter: 只保存包含此域名的 cookie
        filepath: 输出文件路径

    Returns:
        是否成功
    """
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write(f"# Generated by VideoCrawler for {domain_filter}\n\n")

            for c in cookies:
                cookie_domain = c.get("domain", "")
                if domain_filter not in cookie_domain:
                    continue

                name = c.get("name", "")
                # 跳过空 name 的 cookie
                if not name:
                    continue

                value = c.get("value", "")
                path = c.get("path", "/")

                # domain_specified: TRUE 当 domain 以 . 开头
                has_dot = cookie_domain.startswith(".")
                domain_specified = "TRUE" if has_dot else "FALSE"

                # secure
                secure = "TRUE" if c.get("secure") else "FALSE"

                # expires: 0 表示会话 Cookie
                expires = c.get("expires", 0)
                if expires is None or expires < 0:
                    expires = 0
                expires = str(int(expires))

                # Netscape 格式: domain domain_specified path secure expires name value
                f.write(
                    f"{cookie_domain}\t{domain_specified}\t{path}\t"
                    f"{secure}\t{expires}\t{name}\t{value}\n"
                )

        return os.path.getsize(filepath) > 100
    except Exception as e:
        print(f"[cookie] Save error: {e}")
        return False


def fetch_cookies_with_playwright(
    url: str,
    domain: str,
    output_file: Optional[str] = None,
) -> Optional[str]:
    """用 Playwright 启动隐身浏览器访问网站，获取 Cookie

    Args:
        url: 要访问的页面 URL
        domain: 要保存的 Cookie 域名过滤
        output_file: 输出文件路径，None 则自动生成临时文件

    Returns:
        Cookie 文件路径，失败则返回 None
    """
    if output_file is None:
        output_file = os.path.join(tempfile.gettempdir(), "vc_cookies_playwright.txt")

    try:
        from playwright.sync_api import sync_playwright

        with sync_playwright() as p:
            browser = p.chromium.launch(
                headless=True,
                args=[
                    "--no-sandbox",
                    "--disable-blink-features=AutomationControlled",
                ],
            )
            context = browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/120.0.0.0 Safari/537.36"
                ),
                viewport={"width": 1920, "height": 1080},
            )
            page = context.new_page()

            # 使用 'load' 事件（比 networkidle 快很多）
            page.goto(url, wait_until="load", timeout=20000)
            # 额外等待 JS 设置 cookie
            page.wait_for_timeout(3000)

            cookies = context.cookies()
            browser.close()

        if not cookies:
            return None

        if save_cookies_netscape(cookies, domain, output_file):
            return output_file

    except Exception as e:
        print(f"[cookie] Playwright error: {e}")

    return None


def fetch_douyin_cookies(output_file: Optional[str] = None) -> Optional[str]:
    """获取抖音 Cookie（用于视频提取和下载）"""
    return fetch_cookies_with_playwright(
        url="https://www.douyin.com/",
        domain="douyin.com",
        output_file=output_file,
    )


def fetch_tiktok_cookies(output_file: Optional[str] = None) -> Optional[str]:
    """获取 TikTok Cookie"""
    return fetch_cookies_with_playwright(
        url="https://www.tiktok.com/",
        domain="tiktok.com",
        output_file=output_file,
    )
