# -*- coding: utf-8 -*-
"""抖音专用提取器+下载器 v3（2026 版）

2026 年现状（实测结论 2025-08，香港 IP / 未登录环境）：
  - 分享页 https://www.iesdouyin.com/share/video/{id} 已改为纯 JS 壳，
    不再有服务端渲染的 window._ROUTER_DATA
  - 旧接口 https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/ 返回
    {"status_code":11110,"status_msg":"encrypt_data_miss"}（需要 a_bogus 签名）
  - https://www.iesdouyin.com/aweme/v1/web/aweme/detail/ 直接 403 blocked
  - www.douyin.com/aweme/v1/web/aweme/detail/?aweme_id=... 需 a_bogus + msToken 签名
  - 视频页 /video/{id} 对未登录（或海外 IP）用户可能 404 并重定向到精选页，
    页面自己被替换为推荐流 —— 因此拦截视频页的「媒体请求」会把其它视频拿下！
  - yt-dlp 抖音提取器不生成 a_bogus（源码留 TODO），2026 年已基本失效

【2026 可用方案（本模块主路径）】
  抖音网页版全局 hook 了 window.fetch，会自动为同源请求计算 a_bogus 签名。
  因此只需：
    1. 用一个无头/有头浏览器打开 https://www.douyin.com/（首页 200 即可，
       无需目标视频页可访问，海外 IP 也行）
    2. 在页面上下文中 evaluate「fetch(detail API)」—— 签名由页面 hook 自动补全
    3. 校验返回 aweme_detail.aweme_id == 目标 ID（防错拿）
    4. 用浏览器 Cookie 下载 play_addr / bit_rate 直链

  备用路径（hook 失效时）：
    - 视频页渲染 + 详情 API 拦截（同样必须校验目标 ID）
    - CDP 连接用户已登录的 Chrome/Edge（远程调试端口），复用真实登录态
    - yt-dlp + 用户 Cookie 文件
"""

import os
import re
import json
import time
import random
import string
import tempfile
import threading
import urllib.parse
from pathlib import Path
from typing import Optional, Dict, Any, List, Tuple, Callable

try:
    import requests as _requests
except ImportError:  # pragma: no cover
    _requests = None

# ── 常量 ──────────────────────────────────────────────────────
DOUYIN_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36"
)

REFERER_MAIN = "https://www.douyin.com/"
REFERER_SHARE = "https://www.iesdouyin.com/"

# 详情 API 特征（页面 JS 会请求其中一种）
API_MARKERS = (
    "aweme/v1/web/aweme/detail",
    "aweme/v1/web/detail",
    "aweme/detail",
    "aweme/iteminfo",
)

# 视频 CDN 特征（用于请求级兜底抓取）
CDN_MARKERS = (
    "douyinvod.com",
    "zjcdn.com",
    "douyinpic.com",
    "aweme/v1/play",
    "v3-dy",
    "v5-dy",
)

_DEFAULT_TIMEOUT = 45000  # 毫秒


class DouyinError(Exception):
    """抖音提取/下载错误"""


# ── 小工具 ────────────────────────────────────────────────────
def _clean_url(u: str) -> str:
    u = (u or "").strip()
    u = u.replace("\\u0026", "&").replace("\u0026", "&")
    u = u.replace("\\/", "/")
    if u.startswith("http://"):
        u = "https://" + u[7:]
    return u


def _random_token(n: int = 107) -> str:
    """生成 msToken 风格的随机串"""
    return "".join(random.choices(
        string.ascii_letters + string.digits + "-_", k=n))


def extract_video_id(url: str) -> Optional[str]:
    """从 URL 中提取 aweme_id（数字），失败返回 None"""
    m = re.search(r'(?:share/video|video|note|slide)/(\d{14,22})', url)
    if m:
        return m.group(1)
    m = re.search(r'(?:aweme_id|item_ids)=(\d{14,22})', url)
    if m:
        return m.group(1)
    return None


def resolve_share_url(url: str, timeout: int = 15) -> Tuple[str, Optional[str]]:
    """跟随重定向解析分享短链。

    Returns:
        (最终页面URL, aweme_id)
    """
    if _requests is None:
        raise DouyinError("缺少 requests 库")
    # 已经是标准页面链接
    if re.search(r'douyin\.com/(video|note|slide)/\d+', url) \
            and "v.douyin" not in url:
        return url, extract_video_id(url)

    headers = {
        "User-Agent": DOUYIN_UA,
        "Referer": REFERER_SHARE,
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "zh-CN,zh;q=0.9",
    }
    try:
        resp = _requests.get(url, headers=headers, allow_redirects=True,
                             timeout=timeout)
        final = resp.url
    except Exception as e:
        raise DouyinError(f"短链解析失败: {e}")
    if not final or final == url:
        final = url
    return final, extract_video_id(final)


# ── Cookie 工具 ───────────────────────────────────────────────
def cookies_to_requests(cookies: List[dict]) -> Dict[str, str]:
    """Playwright cookie 列表 -> requests cookies dict"""
    out = {}
    for c in cookies or []:
        name, value = c.get("name"), c.get("value")
        if name and value is not None:
            out[name] = value
    return out


def save_cookies_netscape(cookies: List[dict], filepath: str,
                          domain_filter: str = "douyin") -> Optional[str]:
    """Playwright cookie 列表 -> Netscape 格式 cookie 文件（yt-dlp 可用）"""
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by VideoCrawler v3\n\n")
            for c in cookies or []:
                domain = c.get("domain", "")
                if domain_filter and domain_filter not in domain:
                    continue
                name, value = c.get("name", ""), c.get("value", "")
                path = c.get("path", "/")
                has_dot = domain.startswith(".")
                dspec = "TRUE" if has_dot else "FALSE"
                secure = "TRUE" if c.get("secure") else "FALSE"
                expires = c.get("expires") or 0
                expires = 0 if expires <= 0 else int(expires)
                f.write(f"{domain}\t{dspec}\t{path}\t{secure}\t"
                        f"{expires}\t{name}\t{value}\n")
        return filepath if os.path.getsize(filepath) > 50 else None
    except Exception:
        return None


def load_cookies_from_netscape(filepath: str) -> List[dict]:
    """解析 Netscape cookie 文件 -> Playwright cookie 列表"""
    cookies = []
    try:
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t")
                if len(parts) < 7:
                    continue
                domain, _, path, secure, expires, name, value = parts[:7]
                cookies.append({
                    "name": name,
                    "value": value,
                    "domain": domain,
                    "path": path or "/",
                    "secure": secure.lower() == "true",
                    "expires": float(expires) if expires else 0,
                    "httpOnly": False,
                })
    except Exception:
        pass
    return cookies


def build_cookie_header(cookies: List[dict]) -> str:
    return "; ".join(f"{c['name']}={c['value']}"
                     for c in cookies or []
                     if c.get("name") and c.get("value") is not None)


def _temp_cookie_file(cookies: List[dict]) -> Optional[str]:
    if not cookies:
        return None
    path = os.path.join(tempfile.gettempdir(),
                        f"vc_douyin_{int(time.time())}.txt")
    return save_cookies_netscape(cookies, path)


# ── 详情数据解析 ──────────────────────────────────────────────
def parse_aweme_detail(detail: dict) -> Optional[Dict[str, Any]]:
    """从 aweme_detail 中解析视频候选地址与元数据"""
    if not detail:
        return None
    video = detail.get("video") or {}

    candidates: List[Tuple[int, str, str]] = []  # (优先级, url, label)
    seen = set()

def _is_video_like_url(u: str) -> bool:
    """判断 URL 是否像视频下载源（排除配乐 mp3 / 静态图 / 封面）"""
    if re.search(r'(\.mp3(\?|$)|\.m4a(\?|$)|/music|ies-music)',
                 u, re.I):
        return False
    if re.search(r'(\.jpg|\.jpeg|\.png|\.webp|\.heic|\.gif)(\?|$)', u, re.I):
        return False
    if re.search(r'(image|cover|avatar|tplv|webpic)', u, re.I) \
            and "aweme/v1/play" not in u:
        return False
    return True


def parse_aweme_detail(detail: dict) -> Optional[Dict[str, Any]]:
    """从 aweme_detail 中解析视频候选地址与元数据"""
    if not detail:
        return None
    video = detail.get("video") or {}

    candidates: List[Tuple[int, str, str]] = []  # (优先级, url, label)
    seen = set()

    def add(priority: int, urls, label: str):
        for u in urls or []:
            u = _clean_url(u)
            if not u or u in seen:
                continue
            seen.add(u)
            # 排除配乐/封面等非视频源
            if not _is_video_like_url(u):
                continue
            candidates.append((priority, u, label))

    play_addr = video.get("play_addr") or {}
    uri = play_addr.get("uri") or ""
    # 图集/纯音频作品的 play_addr.uri 是完整 mp3 链接，不是视频 ID
    if not re.match(r'^v\d', uri or ""):
        uri = ""
    add(0, play_addr.get("url_list"), "play_addr")

    dl_addr = video.get("download_addr") or {}
    add(1, dl_addr.get("url_list"), "download_addr")

    # 不同码率（画质档位）
    bit_rates: Dict[str, List[str]] = {}
    for br in video.get("bit_rate") or []:
        gear = br.get("gear_name") or ""
        urls = (br.get("play_addr") or {}).get("url_list") or []
        if gear:
            bit_rates.setdefault(gear, [])
        add(3, urls, f"bit_rate:{gear}")
        for u in urls:
            u = _clean_url(u)
            if gear and u and _is_video_like_url(u):
                bit_rates.setdefault(gear, [])
                if u not in bit_rates[gear]:
                    bit_rates[gear].append(u)

    # 用 uri 重建官方播放直链（历史接口，仍会 302 到 CDN）
    if uri:
        for q in ("720p", "1080p", "540p", "360p"):
            rebuilt = (f"https://www.douyin.com/aweme/v1/play/"
                       f"?video_id={uri}&ratio={q}&line=0")
            if rebuilt not in seen:
                seen.add(rebuilt)
                candidates.append((2, rebuilt, f"play_rebuilt:{q}"))

    candidates.sort(key=lambda x: x[0])
    urls = [u for _, u, _ in candidates]
    labels = {u: lab for _, u, lab in candidates}

    # 图集
    images: List[str] = []
    for img in detail.get("images") or []:
        iu = (img.get("url_list") or [])
        if iu:
            # url_list 通常从大到小，取最清晰
            images.append(_clean_url(iu[0]))

    # 元数据
    author = detail.get("author") or {}
    statis = detail.get("statistics") or {}
    video_info = detail.get("video") or {}
    cover = ""
    cover_c = video_info.get("cover") or {}
    if cover_c.get("url_list"):
        cover = _clean_url(cover_c["url_list"][-1])
    else:
        dyn = video_info.get("dynamic_cover") or {}
        if dyn.get("url_list"):
            cover = _clean_url(dyn["url_list"][-1])

    duration_ms = video_info.get("duration") or 0
    duration = duration_ms / 1000.0 if duration_ms else 0

    return {
        "video_id": str(detail.get("aweme_id") or ""),
        "urls": urls,
        "labels": labels,
        "bit_rates": bit_rates,
        "uri": uri,
        "images": images,
        "height": video_info.get("height") or 0,
        "width": video_info.get("width") or 0,
        "duration": duration,
        "title": (detail.get("desc") or "").strip(),
        "uploader": author.get("nickname") or "",
        "uploader_id": author.get("uid") or "",
        "cover": cover,
        "digg_count": statis.get("digg_count") or 0,
        "comment_count": statis.get("comment_count") or 0,
        "share_count": statis.get("share_count") or 0,
        "collect_count": statis.get("collect_count") or 0,
        "play_count": statis.get("play_count") or 0,
        "is_note": bool(detail.get("images")) and not urls,
    }


def parse_quality_rank(gear: str) -> int:
    """从 gear_name 解析画质档位排序（数字越大越好）"""
    g = (gear or "").lower()
    for i, kw in enumerate(("1080", "720", "540", "360")):
        if kw in g:
            base = 4 - i
            if "normal" in g or "higher" in g:
                return base * 10 + 2
            if "high" in g:
                return base * 10 + 1
            return base * 10
    return 0


def collect_from_api_json(payload: dict,
                          target_id: Optional[str] = None
                          ) -> List[Dict[str, Any]]:
    """从 detail 响应收集 aweme 数据（可过滤目标 ID）"""
    results = []
    for key in ("aweme_detail", "aweme_list", "item_list"):
        v = payload.get(key)
        if isinstance(v, list):
            results.extend(v)
        elif isinstance(v, dict) and v.get("aweme_id"):
            results.append(v)
    if target_id:
        results = [d for d in results if str(d.get("aweme_id") or "") == str(target_id)]
    return results


# ── Playwright 浏览器辅助 ─────────────────────────────────────
_STEALTH_JS = """
Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
window.chrome = window.chrome || {runtime: {}};
Object.defineProperty(navigator, 'languages', {
    get: () => ['zh-CN', 'zh', 'en-US', 'en'] });
Object.defineProperty(navigator, 'plugins', { get: () => [
    {name: 'Chrome PDF Plugin', filename: 'internal-pdf-viewer'},
    {name: 'Chrome PDF Viewer', filename: 'mhjfbmdgcfjbbpaeojofohoefgiehjai'},
    {name: 'Native Client', filename: 'internal-nacl-plugin'}] });
try {
    const orig = window.navigator.permissions.query.bind(window.navigator.permissions);
    window.navigator.permissions.query = (p) =>
        p.name === 'notifications'
            ? Promise.resolve({state: Notification.permission})
            : orig(p);
} catch (e) {}
Object.defineProperty(navigator, 'hardwareConcurrency', {get: () => 8});
Object.defineProperty(navigator, 'deviceMemory', {get: () => 8});
"""

# 详情 API 标准 query（device_platform=webapp&aid=6383&channel=channel_pc_web）
_DETAIL_API_QUERY = (
    "device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id={id}"
)

_FETCH_JS = """
async (api) => {
    try {
        const resp = await fetch(api, {credentials: 'include'});
        const text = await resp.text();
        return {status: resp.status, content_type:
                    resp.headers.get('content-type') || '',
                len: text.length, text: text};
    } catch (e) {
        return {error: String(e)};
    }
}
"""


def find_chromium_executable() -> Optional[str]:
    """在常见位置探测 Chromium 可执行文件。

    PyInstaller 打包后 playwright 会把 driver 包内空的 local-browsers
    目录收进 bundle，导致 launch(channel=...) 在打包目录找浏览器而失败；
    这里显式探测用户机器的 ms-playwright（或 PLAYWRIGHT_BROWSERS_PATH），
    存在则用 executable_path 直连。

    Returns:
        chrome.exe 完整路径；找不到返回 None
    """
    candidates = []
    env_path = os.environ.get("PLAYWRIGHT_BROWSERS_PATH", "")
    roots = []
    if env_path:
        roots.append(env_path)
    roots.append(os.path.join(os.environ.get("LOCALAPPDATA", ""),
                              "ms-playwright"))
    roots.append(os.path.join(os.path.expanduser("~"),
                              "AppData", "Local", "ms-playwright"))
    for root in roots:
        if not root or not os.path.isdir(root):
            continue
        for name in ("chromium", "chromium-", "chromium_headless_shell",
                     "chromium_headless_shell-"):
            try:
                for d in os.listdir(root):
                    if d == name or d.startswith(name):
                        for sub in ("chrome-win64", "chrome-win",
                                    "chrome-headless-shell-win64"):
                            p = os.path.join(root, d, sub, "chrome.exe")
                            if os.path.exists(p):
                                candidates.append(p)
                            p2 = os.path.join(root, d, sub,
                                              "chrome-headless-shell.exe")
                            if os.path.exists(p2):
                                candidates.append(p2)
            except Exception:
                continue
    # 优先完整版 chrome（channel=chromium 语义），其次 headless shell
    ordered = sorted(candidates, key=lambda p: ("headless_shell" in p, p))
    return ordered[0] if ordered else None


def _launch_browser(p, headless: bool = True,
                    channel: Optional[str] = "chromium",
                    proxy: Optional[str] = None,
                    cdp_url: Optional[str] = None):
    """启动浏览器（或连接 CDP）。返回 (browser, must_close)"""
    args = [
        "--disable-blink-features=AutomationControlled",
        "--disable-infobars",
        "--no-first-run",
        "--disable-dev-shm-usage",
        "--no-sandbox",
        "--lang=zh-CN",
        "--accept-lang=zh-CN,zh,en",
    ]
    if cdp_url:
        browser = p.chromium.connect_over_cdp(cdp_url)
        return browser, False
    launch_kwargs = {"headless": headless, "args": args}
    # 打包环境修复：显式指向本机 Chromium，避免 playwright 在
    # bundle 内的空 local-browsers 目录找浏览器（channel 与
    # executable_path 互斥，指定后不再传 channel）
    exe = find_chromium_executable()
    if exe:
        launch_kwargs["executable_path"] = exe
    elif channel:
        launch_kwargs["channel"] = channel
    if proxy:
        launch_kwargs["proxy"] = {"server": proxy}
    try:
        browser = p.chromium.launch(**launch_kwargs)
    except Exception:
        if channel and "executable_path" not in launch_kwargs:
            launch_kwargs.pop("channel", None)
            browser = p.chromium.launch(**launch_kwargs)
        else:
            raise
    return browser, True


def _inject_cookies(context, cookies: List[dict]):
    """把 Netscape/Playwright 格式 cookie 注入浏览器上下文"""
    if not cookies:
        return
    try:
        context.add_cookies(cookies)
    except Exception:
        cleaned = []
        for c in cookies:
            c2 = dict(c)
            if c2.get("domain", "").startswith("."):
                c2["domain"] = c2["domain"].lstrip(".")
            cleaned.append(c2)
        try:
            context.add_cookies([c for c in cleaned if c.get("name")])
        except Exception:
            pass


def _fetch_detail_in_page(
    page,
    aweme_id: str,
    attempts: int = 6,
    wait_between: float = 2.0,
) -> Optional[dict]:
    """在页面上下文中用 fetch 调详情 API（页面 hook 自动补 a_bogus 签名）。

    返回解析后的 aweme_detail dict；失败返回 None
    """
    api = ("https://www.douyin.com/aweme/v1/web/aweme/detail/?"
           + _DETAIL_API_QUERY.format(id=aweme_id))
    for i in range(attempts):
        try:
            r = page.evaluate(_FETCH_JS, api)
        except Exception:
            r = None
        if r and r.get("status") == 200 and r.get("len", 0) > 200:
            try:
                payload = json.loads(r["text"])
            except Exception:
                payload = None
            if payload:
                details = collect_from_api_json(payload, target_id=aweme_id)
                if details:
                    return details[0]
                # 有数据但不是目标 ID —— 异常，别返回
                return None
        time.sleep(wait_between)
    return None


# ── 提取主流程 ────────────────────────────────────────────────
def extract_douyin_video(
    url: str,
    timeout: int = _DEFAULT_TIMEOUT,
    headless: bool = True,
    channel: Optional[str] = "chromium",
    proxy: Optional[str] = None,
    login_cookie_file: Optional[str] = None,
    cdp_url: Optional[str] = None,
    use_ytdlp_fallback: bool = True,
    progress_cb: Optional[Callable] = None,
) -> Dict[str, Any]:
    """提取抖音视频信息（多路径 + 目标一致性校验）

    Args:
        url: 抖音链接（短链 v.douyin.com / 视频页 / note 图集 / 分享链接）
        timeout: 页面加载超时（毫秒）
        headless: 无头模式（False 会弹出浏览器窗口）
        channel: 浏览器通道 "chromium"(完整内核new-headless) / "msedge" / "chrome" / ""
        proxy: 代理服务器地址（如 http://127.0.0.1:7890）
        login_cookie_file: Netscape 格式 Cookie 文件（登录态，最稳
            —— 从浏览器导出 douyin.com 的 Cookie 即可）
        cdp_url: 连接已打开的 Chrome/Edge 远程调试端口
            （如 http://127.0.0.1:9222，浏览器需 --remote-debugging-port=9222）
        use_ytdlp_fallback: 是否在提取失败后用 yt-dlp + Cookie 兜底
        progress_cb: 进度回调 (msg: str)

    Returns:
        {
          success, method, video_id, title, uploader, description, duration,
          cover, images, urls(候选直链/优先排序), bit_rates, uri,
          width, height, digg_count, ..., cookies, cookie_file,
          video_srcs, final_url, redirected, page_ok, error
        }
    """
    if progress_cb:
        progress_cb("解析分享链接...")
    try:
        final_url, aweme_id = resolve_share_url(url)
    except DouyinError as e:
        return {"success": False, "error": str(e), "urls": [], "cookies": []}

    if not aweme_id:
        m = re.search(r'(?:/video/|/note/|/slide/|share/video/)(\d+)', final_url)
        if m:
            aweme_id = m.group(2)
    if not aweme_id:
        # 短链被重定向到抖音首页/精选页 => 链接在服务器侧已失效
        if re.search(r'douyin\.com/?$', final_url) or "jingxuan" in final_url \
                or not re.search(r'douyin', final_url):
            return {"success": False, "urls": [], "cookies": [],
                    "error": (
                        "链接已失效（抖音服务器无法找到该视频）\n\n"
                        "服务器把分享短链重定向到了抖音首页/精选页，"
                        "通常意味着：\n"
                        "  • 视频已被作者删除或转为私密/仅粉丝可见\n"
                        "  • 分享链接已过期，或被平台屏蔽/下架\n\n"
                        "请打开抖音 App，找到该视频确认是否还能点开：\n"
                        "  • 能点开 → 重新点「分享 → 复制链接」，用新链接重试\n"
                        "  • 点不开 → 该视频已不可下载"
                    )}
        return {"success": False, "error":
                "未能从链接中解析出视频 ID：" + str(final_url)[:100],
                "urls": [], "cookies": []}

    if proxy:
        proxy = proxy.strip() or None

    base = {
        "success": False, "error": "", "method": "",
        "urls": [], "cookies": [], "bit_rates": {}, "images": [],
        "video_id": aweme_id, "final_url": final_url,
        "redirected": False, "page_ok": False,
    }
    err_msgs: List[str] = []

    # 登录 Cookie（文件）优先注入
    extra_cookies = []
    if login_cookie_file and Path(login_cookie_file).exists():
        extra_cookies = load_cookies_from_netscape(login_cookie_file)
        if progress_cb:
            progress_cb(f"已加载登录 Cookie（{len(extra_cookies)} 条）")

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        return {**base, "error":
                "缺少 playwright，请先安装:\n"
                "  pip install playwright\n"
                "  python -m playwright install chromium"}

    # ── 路径1：首页上下文 fetch 详情 API（主路径） ──
    try:
        with sync_playwright() as p:
            browser, must_close = _launch_browser(
                p, headless=headless, channel=channel, proxy=proxy,
                cdp_url=cdp_url)
            try:
                contexts = browser.contexts
                if cdp_url and contexts:
                    # CDP：复用已有 context（含登录态）
                    context = contexts[0]
                    _inject_cookies(context, extra_cookies)
                    pages = context.pages
                    new_page = False
                    if not pages:
                        page = context.new_page()
                        new_page = True
                    else:
                        page = pages[0]
                        new_page = False
                else:
                    context = browser.new_context(
                        user_agent=DOUYIN_UA,
                        viewport={"width": 1440, "height": 900},
                        device_scale_factor=1,
                        locale="zh-CN", timezone_id="Asia/Shanghai",
                        color_scheme="light",
                    )
                    context.add_init_script(_STEALTH_JS)
                    _inject_cookies(context, extra_cookies)
                    page = context.new_page()
                    new_page = True

                if progress_cb:
                    progress_cb("打开抖音首页（建立签名环境）...")
                try:
                    page.goto("https://www.douyin.com/",
                              wait_until="domcontentloaded",
                              timeout=min(timeout, 40000))
                    page_ok = True
                except Exception as e:
                    page_ok = False
                    err_msgs.append(f"首页加载: {str(e)[:120]}")
                base["page_ok"] = page_ok

                if page_ok:
                    page.wait_for_timeout(3000)
                    if progress_cb:
                        progress_cb("请求详情 API（页面自动签名）...")
                    detail = _fetch_detail_in_page(
                        page, aweme_id, attempts=6, wait_between=2.0)
                else:
                    detail = None

                cookies = [dict(c) for c in context.cookies()
                           if "douyin" in c.get("domain", "")]
                base["cookies"] = cookies

                if detail:
                    parsed = parse_aweme_detail(detail)
                    if parsed:
                        parsed["cookies"] = cookies
                        parsed["cookie_file"] = _temp_cookie_file(cookies)
                        parsed["method"] = "page_fetch"
                        parsed["page_ok"] = page_ok
                        parsed["final_url"] = final_url
                        base.update(parsed)
                        base["success"] = bool(parsed.get("urls")
                                               or parsed.get("images"))
                        if not base["success"]:
                            base["error"] = "详情为空：作品可能已被删除或私密"
                        return base
                    else:
                        err_msgs.append("详情解析失败")
                else:
                    err_msgs.append("detail API 未返回目标数据")
            finally:
                if must_close:
                    try:
                        browser.close()
                    except Exception:
                        pass
    except Exception as e:
        err_msgs.append(f"浏览器: {str(e)[:150]}")

    # ── 路径2：视频页渲染 + 详情 API 拦截（页面自身会拉详情） ──
    try:
        result = _launch_playwright_page(
            aweme_id, final_url, timeout=timeout, headless=headless,
            channel=channel, proxy=proxy, login_cookies=extra_cookies)
        if result and result.get("success"):
            result.update({
                "video_id": aweme_id, "final_url": final_url,
                "page_ok": result.get("page_ok", True),
            })
            return result
        if result and result.get("error"):
            err_msgs.append(result["error"])
    except Exception as e:
        err_msgs.append(f"页面渲染: {str(e)[:150]}")

    # ── 路径3：yt-dlp + Cookie 兜底 ──
    if use_ytdlp_fallback:
        try:
            cookies = base.get("cookies") or extra_cookies
            r = _extract_via_ytdlp(final_url, cookies, channel=channel,
                                   headless=headless, proxy=proxy)
            if r and r.get("urls"):
                r["video_id"] = aweme_id
                r["final_url"] = final_url
                return r
        except Exception as e:
            err_msgs.append(f"ytdlp: {str(e)[:100]}")

    base["error"] = ("；".join(err_msgs) or "所有路径均失败") + (
        "\n\n诊断建议：\n"
        "1. 作品可能已删除/设为私密/仅粉丝可见 —— 先用手机抖音确认能否播放\n"
        "2. 需要登录态: 在浏览器里登录抖音后导出 douyin.com 的 Cookie\n"
        "   （chrome 扩展 Get cookies.txt / 程序菜单 设置→Cookie 文件），\n"
        "   然后用: python cli.py <链接> --login-cookie cookies.txt\n"
        "3. 或连接已登录浏览器: 关闭浏览器后以\n"
        "   msedge --remote-debugging-port=9222 启动，再\n"
        "   python cli.py <链接> --cdp http://127.0.0.1:9222\n"
        "4. 若网络出口在境外, 抖音可能限制视频页; 可加 --proxy 使用国内代理\n"
        "5. 若提示浏览器内核缺失（Windows 版）: 从 Release 下载\n"
        "   chromium-win64.zip，解压到 %LOCALAPPDATA%\\ms-playwright"
    )
    return base


# ── 路径2 实现：视频页渲染拦截 ───────────────────────────────
def _launch_playwright_page(
    aweme_id: str,
    final_url: str,
    timeout: int = _DEFAULT_TIMEOUT,
    headless: bool = True,
    channel: Optional[str] = "chromium",
    proxy: Optional[str] = None,
    login_cookies: Optional[List[dict]] = None,
) -> Optional[Dict[str, Any]]:
    """打开目标视频页面（或 share 页），拦截目标 ID 的详情 API 响应"""
    from playwright.sync_api import sync_playwright

    pages_to_try = []
    for url in (
        f"https://www.douyin.com/video/{aweme_id}",
        f"https://www.douyin.com/discover?modal_id={aweme_id}",
        f"https://www.iesdouyin.com/share/video/{aweme_id}/",
    ):
        pages_to_try.append(url)
    if final_url and "douyin" in final_url:
        pages_to_try.append(final_url)
    seen = set()
    pages_to_try = [u for u in pages_to_try
                    if not (u in seen or seen.add(u))]

    try:
        with sync_playwright() as p:
            browser, must_close = _launch_browser(
                p, headless=headless, channel=channel, proxy=proxy)
            try:
                context = browser.new_context(
                    user_agent=DOUYIN_UA,
                    viewport={"width": 1440, "height": 900},
                    device_scale_factor=1, locale="zh-CN",
                    timezone_id="Asia/Shanghai", color_scheme="light",
                )
                context.add_init_script(_STEALTH_JS)
                _inject_cookies(context, login_cookies or [])
                page = context.new_page()

                hits = []
                media_urls = []

                def on_response(resp):
                    u = resp.url
                    if any(m in u for m in API_MARKERS):
                        try:
                            data = resp.json()
                        except Exception:
                            data = {}
                        if isinstance(data, dict):
                            hits.append((resp.status, u, data))
                    elif any(m in u for m in CDN_MARKERS):
                        media_urls.append(u)

                page.on("response", on_response)

                for i, page_url in enumerate(pages_to_try):
                    try:
                        page.goto(page_url, wait_until="domcontentloaded",
                                  timeout=min(timeout, 40000))
                        page.wait_for_timeout(6000)
                    except Exception:
                        pass
                    # 在页面上下文里再试一次 fetch（hook 已装）
                    detail = _fetch_detail_in_page(page, aweme_id,
                                                   attempts=3,
                                                   wait_between=1.0)
                    if detail:
                        parsed = parse_aweme_detail(detail)
                        if parsed:
                            cookies = [dict(c) for c in context.cookies()
                                       if "douyin" in c.get("domain", "")]
                            parsed.update({
                                "cookies": cookies,
                                "cookie_file": _temp_cookie_file(cookies),
                                "method": "page_render",
                                "page_ok": True,
                                "final_url": page_url,
                            })
                            return parsed
                    # 匹配目标 ID 的拦截响应
                    for st, u, data in hits:
                        if st == 200:
                            details = collect_from_api_json(data,
                                                            target_id=aweme_id)
                            if details:
                                parsed = parse_aweme_detail(details[0])
                                if parsed:
                                    cookies = [dict(c) for c in context.cookies()
                                               if "douyin" in c.get("domain", "")]
                                    parsed.update({
                                        "cookies": cookies,
                                        "cookie_file": _temp_cookie_file(
                                            cookies),
                                        "method": "page_render",
                                        "page_ok": True,
                                        "final_url": page_url,
                                    })
                                    return parsed
                try:
                    page_ok = True
                    final_page = page.url
                except Exception:
                    page_ok = False
                    final_page = ""
                redirected = final_page and aweme_id not in final_page
                cookies = [dict(c) for c in context.cookies()
                           if "douyin" in c.get("domain", "")]
                return {
                    "success": False, "method": "page_render",
                    "urls": [], "cookies": cookies, "images": [],
                    "page_ok": page_ok, "redirected": redirected,
                    "error": ("视频页不可达（被重定向/404），详情 API 未返回"
                              "目标数据"),
                }
            finally:
                if must_close:
                    try:
                        browser.close()
                    except Exception:
                        pass
    except Exception as e:
        return {"success": False, "urls": [], "cookies": [],
                "error": f"渲染失败: {str(e)[:150]}"}


# ── 路径3 实现：yt-dlp + Cookie ──────────────────────────────
def _extract_via_ytdlp(
    url: str,
    cookies: List[dict],
    timeout: int = 60000,
    headless: bool = True,
    channel: Optional[str] = "chromium",
    proxy: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """yt-dlp + 最新 Cookie 提取（备用路径；yt-dlp 自身不生成签名）"""
    import yt_dlp

    cookie_file = _temp_cookie_file(cookies) if cookies else None
    if not cookie_file:
        cookie_file = _fetch_cookies_fast(headless=headless, channel=channel,
                                          proxy=proxy)

    opts = {
        "quiet": True,
        "no_warnings": True,
        "noplaylist": True,
        "extract_flat": False,
        "socket_timeout": 30,
    }
    if cookie_file:
        opts["cookiefile"] = cookie_file
    if proxy:
        opts["proxy"] = proxy

    class _L:
        def debug(self, msg): pass
        def warning(self, msg): pass
        def error(self, msg): pass

    opts["logger"] = _L()

    with yt_dlp.YoutubeDL(opts) as ydl:
        try:
            info = ydl.extract_info(url, download=False)
        except Exception as e:
            raise DouyinError(f"yt-dlp: {e}") from e

    if not info:
        return None
    if info.get("entries"):
        info = info["entries"][0]

    formats = info.get("formats") or []

    def score(f):
        return (f.get("height") or 0) * 100 + (f.get("tbr") or 0)

    best_f = max(formats, key=score) if formats else None
    url_list = []
    seen = set()
    if best_f and best_f.get("url"):
        u = _clean_url(best_f["url"])
        seen.add(u)
        url_list.append(u)
    for f in formats:
        u = _clean_url(f.get("url") or "")
        if u and u not in seen and not u.startswith(("blob:", "data:")):
            seen.add(u)
            url_list.append(u)

    return {
        "success": bool(url_list),
        "method": "ytdlp",
        "video_id": str(info.get("id") or ""),
        "urls": url_list,
        "labels": {},
        "bit_rates": {},
        "uri": "",
        "images": [],
        "duration": float(info.get("duration") or 0),
        "title": info.get("title") or "",
        "uploader": info.get("uploader") or info.get("channel") or "",
        "cover": info.get("thumbnail") or "",
        "cookies": cookies,
        "cookie_file": cookie_file,
        "error": "" if url_list else "yt-dlp 未返回可用直链",
    }


def _fetch_cookies_fast(headless: bool = True,
                        channel: Optional[str] = None,
                        proxy: Optional[str] = None) -> Optional[str]:
    """快速打开抖音首页获取一次 Cookie（用于 yt-dlp 兜底）"""
    from playwright.sync_api import sync_playwright
    try:
        with sync_playwright() as p:
            browser, must_close = _launch_browser(
                p, headless=headless, channel=channel, proxy=proxy)
            try:
                context = browser.new_context(
                    user_agent=DOUYIN_UA,
                    viewport={"width": 1440, "height": 900},
                    locale="zh-CN", timezone_id="Asia/Shanghai")
                context.add_init_script(_STEALTH_JS)
                page = context.new_page()
                page.goto("https://www.douyin.com/",
                          wait_until="domcontentloaded", timeout=20000)
                page.wait_for_timeout(4000)
                cookies = [dict(c) for c in context.cookies()
                           if "douyin" in c.get("domain", "")]
                return _temp_cookie_file(cookies)
            finally:
                if must_close:
                    try:
                        browser.close()
                    except Exception:
                        pass
    except Exception:
        return None


# ── 下载 ──────────────────────────────────────────────────────
def _pick_download_url(
    urls: List[str],
    session,
    headers: Dict[str, str],
    preferred: Optional[str] = None,
) -> Tuple[Optional[str], int]:
    """HEAD 探测候选地址，返回 (url, size)。

    优先官方调度接口（aweme/v1/play，会 302 到合适的 CDN 节点），
    保证大陆用户拿到国内高速节点。
    """
    def sort_key(u):
        if "aweme/v1/play" in u:
            return 0
        if "zjcdn" in u or "douyinvod" in u:
            return 1
        return 2

    order = list(urls)
    order.sort(key=sort_key)
    if preferred and preferred in order:
        order.remove(preferred)
        order.insert(0, preferred)
    for u in order:
        try:
            resp = session.head(u, headers=headers, timeout=15,
                                allow_redirects=True)
            if resp.status_code in (200, 206) and int(
                    resp.headers.get("content-length", 0) or 0) > 0:
                ctype = resp.headers.get("content-type", "")
                if "video" in ctype or "octet-stream" in ctype \
                        or "aweme/v1/play" in u:
                    return u, int(resp.headers.get("content-length", 0))
        except Exception:
            continue
    return None, 0


def _select_urls_by_quality(result: Dict[str, Any],
                            quality_hint: str = "best") -> List[str]:
    """按画质档位挑选候选 URL 顺序（原顺序兜底）"""
    urls = result.get("urls") or []
    if not urls:
        return urls
    if not quality_hint or quality_hint == "best":
        return urls
    idea = str(quality_hint).lower().replace("p", "")
    bit_rates = result.get("bit_rates") or {}
    # 档位匹配：先按 gear 排序筛选
    ranked = []
    for gear, us in bit_rates.items():
        rank = parse_quality_rank(gear)
        if idea in gear.lower():
            rank += 1000
        ranked.append((rank, gear, us))
    ranked.sort(key=lambda x: -x[0])
    matched = [r for r in ranked if r[0] >= 1000]
    if matched:
        first = matched[0][2]
        return first + [u for u in urls if u not in first]
    return urls


def download_douyin_video(
    page_url: str,
    output_dir: str,
    filename: str = "抖音视频",
    timeout: int = 120000,
    progress_cb: Optional[Callable] = None,
) -> Optional[str]:
    """完整流程：提取 → 下载（兼容旧接口）

    Returns:
        下载完成的文件路径，失败返回 None
    """
    result = extract_douyin_video(page_url, timeout=60000)
    if not result.get("success"):
        print(f"[抖音] 提取失败: {result.get('error', '未知错误')}")
        return None
    try:
        data = download_douyin_result(result, output_dir, filename,
                                      progress_cb=progress_cb)
        return data
    except DouyinError as e:
        print(f"[抖音] 下载失败: {e}")
        return None


def download_douyin_result(
    result: Dict[str, Any],
    output_dir: str,
    filename: str = "抖音视频",
    progress_cb: Optional[Callable] = None,
    cancel_event: Optional[threading.Event] = None,
    quality: str = "best",
    timeout: int = 120000,
) -> str:
    """根据提取结果直接下载（供 GUI 使用）

    Args:
        result: extract_douyin_video 的返回
        output_dir: 输出目录
        filename: 文件名（不含扩展名）
        progress_cb: 回调 (downloaded_bytes, total_bytes, status)
        cancel_event: 取消事件
        quality: 画质档位 "best"/"1080p"/"720p"/"540p"/"360p"

    Returns:
        文件绝对路径
    """
    if _requests is None:
        raise DouyinError("缺少 requests 库")

    urls = _select_urls_by_quality(result, quality)
    if not urls:
        # 图集无视频
        if result.get("images"):
            files = download_douyin_images(
                result, output_dir, filename, progress_cb=progress_cb,
                cancel_event=cancel_event)
            return files[0] if files else ""
        raise DouyinError("没有可用的视频地址")

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    safe_name = re.sub(r'[\x00-\x1f\\/:*?"<>|\r\n#]', '_',
                       str(filename)).strip('._ ') or "douyin_video"
    safe_name = re.sub(r'_+', '_', safe_name)[:80]

    cookies = result.get("cookies") or []
    session = _requests.Session()
    for c in cookies:
        if c.get("name") and c.get("value") is not None:
            session.cookies.set(c["name"], c["value"],
                                domain=c.get("domain", ""),
                                path=c.get("path", "/"))

    headers = {
        "User-Agent": DOUYIN_UA,
        "Referer": REFERER_MAIN,
        "Origin": "https://www.douyin.com",
        "Accept": "video/mp4,video/*;q=0.9,*/*;q=0.8",
        "Accept-Language": "zh-CN,zh;q=0.9",
    }
    if cookies:
        headers["Cookie"] = build_cookie_header(cookies)

    # 探测最优地址
    url, size = _pick_download_url(urls, session, headers,
                                   preferred=urls[0])
    if not url:
        # 最后兜底：GET 试一次
        for u in urls:
            try:
                resp = session.get(u, headers=headers, stream=True, timeout=20)
                if resp.status_code == 200:
                    chunk = next(resp.iter_content(4096))
                    if chunk:
                        url, size = u, int(
                            resp.headers.get("content-length", 0) or 0)
                        break
            except Exception:
                continue
    if not url:
        raise DouyinError("所有候选视频地址均不可用")

    filepath = output_path / f"{safe_name}.mp4"
    counter = 1
    while filepath.exists() or (output_path / f"{safe_name}.mp4.part").exists():
        filepath = output_path / f"{safe_name}_{counter}.mp4"
        counter += 1
    part_file = output_path / (filepath.name + ".part")

    if progress_cb:
        progress_cb(0, size or 0, "start")

    # 断点续传 + 多源重试
    valid_urls = [url] + [u for u in urls if u != url]
    last_err: Optional[str] = None
    done = False
    downloaded = 0
    total = size or 0

    for attempt in range(3):
        for u in valid_urls[:8]:
            if cancel_event and cancel_event.is_set():
                raise DouyinError("下载已取消")
            try:
                offset = part_file.stat().st_size if part_file.exists() else 0
                req_headers = dict(headers)
                if offset > 0:
                    req_headers["Range"] = f"bytes={offset}-"

                resp = session.get(u, headers=req_headers, stream=True,
                                   timeout=timeout, allow_redirects=True)
                if resp.status_code not in (200, 206):
                    continue
                if offset > 0 and resp.status_code == 200:
                    # 服务器不支持断点，重新开始
                    offset = 0
                    if part_file.exists():
                        part_file.unlink()

                mode = "ab" if offset > 0 and resp.status_code == 206 else "wb"
                cur_total = int(
                    resp.headers.get("content-length", 0) or 0)
                if mode == "wb":
                    downloaded = 0
                    total = cur_total or total
                else:
                    downloaded = offset
                    total = offset + (cur_total or 0)
                body_total = total or 0

                with open(part_file, mode) as f:
                    for chunk in resp.iter_content(chunk_size=64 * 1024):
                        if cancel_event and cancel_event.is_set():
                            raise DouyinError("下载已取消")
                        if chunk:
                            f.write(chunk)
                            downloaded += len(chunk)
                            if progress_cb:
                                progress_cb(downloaded, body_total,
                                            "downloading")

                done = True
                break
            except DouyinError:
                raise
            except Exception as e:
                last_err = str(e)
                continue
        if done:
            break
        time.sleep(2)

    if not done:
        if part_file.exists():
            try:
                part_file.unlink()
            except Exception:
                pass
        raise DouyinError(f"下载失败: {last_err or '所有源均不可用'}")

    # 校验并改名为正式文件
    if part_file.stat().st_size == 0:
        part_file.unlink()
        raise DouyinError("文件为空，下载失败")
    try:
        os.replace(part_file, filepath)
    except Exception:
        # 改名失败则保留 part（重试场景）
        pass

    if progress_cb:
        progress_cb(downloaded, total or downloaded, "finished")
    return str(filepath.resolve())


def _looks_video_url(url: str) -> bool:
    return bool(re.search(r'(mp4|video|play|zjcdn|douyinvod|bytovod|aweme/v1/play)',
                          url, re.I))


# ── 图片（图集）下载 ──────────────────────────────────────────
_IMAGE_EXT_BY_CTYPE = {
    "image/webp": ".webp",
    "image/jpeg": ".jpg",
    "image/jpg": ".jpg",
    "image/png": ".png",
    "image/avif": ".avif",
    "image/heic": ".heic",
    "image/heif": ".heif",
    "image/gif": ".gif",
}


def _convert_image_bytes(data: bytes, target: str) -> bytes:
    """用 Pillow 把图片字节转换为目标格式（jpg/png/webp）。target 未知时原样返回。

    - jpg: 含透明通道时合成白底（避免透明变黑）
    - png: 保留透明
    - webp: quality 92
    """
    if not data or not target or target == "keep":
        return data
    import io as _io
    from PIL import Image
    try:
        img = Image.open(_io.BytesIO(data))
        out = _io.BytesIO()
        fmt = target.lower()
        if fmt in ("jpg", "jpeg", "jfif"):
            img = img.convert("RGBA") if img.mode in ("RGBA", "LA") or (
                img.mode == "P" and "transparency" in img.info) else img
            if img.mode == "RGBA":
                bg = Image.new("RGB", img.size, (255, 255, 255))
                bg.paste(img, mask=img.split()[3])
                img = bg
            elif img.mode != "RGB":
                img = img.convert("RGB")
            img.save(out, "JPEG", quality=92)
            return out.getvalue()
        if fmt == "png":
            if img.mode == "P":
                img = img.convert("RGBA")
            elif img.mode not in ("RGB", "RGBA", "L"):
                img = img.convert("RGBA")
            img.save(out, "PNG")
            return out.getvalue()
        if fmt == "webp":
            img.save(out, "WEBP", quality=92)
            return out.getvalue()
    except Exception:
        return data  # 转换失败时保底用原始数据
    return data


_IMAGE_FORMAT_EXT = {
    "jpg": ".jpg", "jpeg": ".jpg", "jfif": ".jpg",
    "png": ".png", "webp": ".webp", "gif": ".gif",
    "keep": "",
}


def _detect_image_ext(ctype: str, img_url: str) -> str:
    ext = _IMAGE_EXT_BY_CTYPE.get(ctype.split(";")[0].strip().lower(), "")
    if not ext:
        m = re.search(r'\.(webp|jpg|jpeg|png|avif|heic|heif|gif)(\?|$)',
                      img_url, re.I)
        ext = {"jpeg": ".jpg"}.get(
            (m.group(1) if m else "").lower(),
            f".{(m.group(1) if m else 'jpg').lower()}")
    return ext or ".jpg"


def download_douyin_images(
    result: Dict[str, Any],
    output_dir: str,
    filename: str = "抖音图集",
    progress_cb: Optional[Callable] = None,
    cancel_event: Optional[threading.Event] = None,
    image_format: str = "jpg",
) -> List[str]:
    """下载图集（note/图文）图片并按目标格式保存。返回文件路径列表。

    Args:
        image_format: 保存格式 jpg/png/webp/keep（keep=保持源格式）
    """
    if _requests is None:
        raise DouyinError("缺少 requests 库")
    images = result.get("images") or []
    if not images:
        raise DouyinError("该作品不是图集")

    fmt = (image_format or "jpg").lower().strip()
    fmt = "jpg" if fmt in ("jpeg", "jfif") else fmt
    out_ext = _IMAGE_FORMAT_EXT.get(fmt, ".jpg")

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    safe_name = re.sub(r'[\x00-\x1f\\/:*?"<>|\r\n#]', '_',
                       str(filename)).strip('._ ') or "douyin_note"
    safe_name = re.sub(r'_+', '_', safe_name)[:80]

    cookies = result.get("cookies") or []
    session = _requests.Session()
    for c in cookies:
        if c.get("name") and c.get("value") is not None:
            session.cookies.set(c["name"], c["value"],
                                domain=c.get("domain", ""),
                                path=c.get("path", "/"))

    headers = {
        "User-Agent": DOUYIN_UA,
        "Referer": REFERER_MAIN,
        "Accept": "image/webp,image/apng,image/*,*/*;q=0.8",
    }
    if cookies:
        headers["Cookie"] = build_cookie_header(cookies)

    saved = []
    for i, img_url in enumerate(images, 1):
        img_url = _clean_url(img_url)
        tmp_file = output_path / f"{safe_name}_{i:02d}.part"
        try:
            resp = session.get(img_url, headers=headers, stream=True,
                               timeout=60, allow_redirects=True)
            resp.raise_for_status()
            # 目标扩展名：指定格式 → 该格式；keep → 按 Content-Type/URL 检测
            if out_ext:
                ext = out_ext
            else:
                ctype = (resp.headers.get("content-type") or "")
                ext = _detect_image_ext(ctype, img_url)
            fpath = output_path / f"{safe_name}_{i:02d}{ext}"

            # 读出源字节
            from io import BytesIO
            buf = BytesIO()
            for chunk in resp.iter_content(chunk_size=64 * 1024):
                if cancel_event and cancel_event.is_set():
                    raise DouyinError("下载已取消")
                if chunk:
                    buf.write(chunk)
            raw = buf.getvalue()
            if out_ext:
                data = _convert_image_bytes(raw, fmt)
            else:
                data = raw
            if not data:
                raise DouyinError("图片数据为空")

            with open(tmp_file, "wb") as f:
                f.write(data)
            if tmp_file.exists() and tmp_file.stat().st_size > 0:
                os.replace(tmp_file, fpath)
            if progress_cb:
                progress_cb(i, len(images), "image_done")
            saved.append(str(fpath.resolve()))
        except DouyinError:
            raise
        except Exception as e:
            for p in (tmp_file,):
                if p.exists():
                    try:
                        p.unlink()
                    except Exception:
                        pass
            raise DouyinError(f"第 {i} 张图片下载失败: {e}") from e

    return saved
